# Generated by Django 4.1.7 on 2023-03-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('is_Free', models.BooleanField()),
                ('Price', models.FloatField()),
            ],
        ),
    ]
