# Generated by Django 4.1.7 on 2023-03-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_room_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_types',
            field=models.IntegerField(choices=[(1, 'Стая – две единични легла'), (2, 'Апартамент'), (3, 'Стая с двойно легло'), (4, 'Пентхаус'), (5, 'Мезонет')]),
        ),
    ]
