# Generated by Django 4.1.7 on 2023-03-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_room_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Description',
            field=models.TextField(default='(Description here)'),
        ),
    ]
