# Generated by Django 4.1.7 on 2023-03-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_room', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('including_breakfast', models.BooleanField()),
                ('all_inclusive', models.BooleanField()),
                ('cost', models.FloatField()),
            ],
        ),
    ]
